changelog:
    exclude:
        labels:
            - tagpr
    categories:
        - title: 'Feature changes'
          labels:
              - 'Type: New Feature'
        - title: 'Patch changes'
          labels:
              - 'Problem: Bug'
        - title: 'Maintenance and internal'
          labels:
              - '*'
