changelog:
  exclude:
    labels:
      - tagpr
  categories:
    - title: Features
      labels:
        - 'Release: Features'
    - title: Fixes
      labels:
        - 'Release: Fixes'
    - title: Improvements
      labels:
        - 'Release: Improvements'
    - title: Performance
      labels:
        - 'Release: Performance'
    - title: Documentation
      labels:
        - 'Release: Documentation'
    - title: Tests
      labels:
        - 'Release: Tests'
    - title: Chores
      labels:
        - 'Release: Chores'
    - title: Design
      labels:
        - 'Release: Design'
    - title: Other Changes
      labels:
        - '*'
